In [1]:
%load_ext sql

In [79]:
%sql mysql://admin:sql_2020@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project

'Connected: admin@sql_project'

In [108]:
%%sql
SELECT *
FROM artists
WHERE artist_genre LIKE '%pop%'
ORDER BY artist_popularity DESC;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
24 rows affected.

[(1, '3TVXtAsR1Inumwj472S9r4', 'Drake', 'canadian hip hop, canadian pop, hip hop, pop rap, rap, toronto rap', 99),
 (0, '1Xyo4u8uXC1ZmMpatF05PJ', 'The Weeknd', 'canadian contemporary r&b, canadian pop, pop', 98),
 (3, '6M2wZ9GZgrQXHCFfjv46we', 'Dua Lipa', 'dance pop, pop, uk pop', 96),
 (32, '6qqNVTkY8uBg9cP3Jd7DAH', 'Billie Eilish', 'electropop, pop', 96),
 (11, '1uNFoZAHBGtllmzznpCI3s', 'Justin Bieber', 'canadian pop, pop, post-teen pop', 95),
 (31, '1RyvyyTE3xzB2ZywiAwp0i', 'Future', 'atl hip hop, pop rap, rap, southern hip hop, trap', 92),
 (8, '5cj0lLjcoR7YOSnhnX0Po5', 'Doja Cat', 'la indie, pop', 91),
 (20, '4GNC7GD6oZMSxPGyXy4MNB', 'Lewis Capaldi', 'pop, uk pop', 90),
 (26, '2wY79sveU1sp5g7SokKOiI', 'Sam Smith', 'pop, post-teen pop, uk pop', 90),
 (29, '6KImCVD70vtIoJWnq6nGn3', 'Harry Styles', 'pop, post-teen pop', 90),
 (30, '04gDigrS5kc9YWfZHwBETP', 'Maroon 5', 'pop, pop rock', 90),
 (36, '7n2wHs1TKAczGzO7Dd2rGr', 'Shawn Mendes', 'canadian pop, pop, post-teen pop, viral pop', 90),
 (2, '0H39MdGGX6dbnnQPt6NQkZ', 'SAINt JHN', 'melodic rap, pop rap, rap, trap', 88),
 (5, '2NjfBq1NflQcKSeiDooVjY', 'Tones And I', 'australian pop', 88),
 (28, '28gNT5KBp7IjEOQoevXf9N', 'Camilo', 'colombian pop, latin', 88),
 (16, '181bsRPaVXVlUKXrxwZfHK', 'Megan Thee Stallion', 'houston rap, pop, pop rap, trap queen', 86),
 (13, '7uaIm6Pw7xplS8Dy06V6pT', 'Trevor Daniel', 'alternative r&b, melodic rap, pop rap', 85),
 (14, '4ETSs924pXMzjIeD6E9b4u', 'Surfaces', 'bedroom soul, pop', 85),
 (12, '0Cp8WN4V8Tu4QJQwCN5Md4', 'BENEE', 'nz pop, pop', 84),
 (19, '0vRvGUQVUjytro0xpb26bs', 'Arizona Zervas', 'pop rap', 84),
 (27, '2LIk90788K0zvyj2JJVwkJ', 'Jack Harlow', 'deep underground hip hop, hip hop, pop rap, rap, trap, underground hip hop', 82),
 (48, '0xRXCcSX89eobfrshSVdyu', 'MEDUZA', 'pop house', 82),
 (41, '66W9LaWS0DPdL7Sz8iYGYe', 'JP Saxe', 'canadian contemporary r&b, pop', 80),
 (46, '4ofCBoyEiGSePFAG500xev', 'Regard', 'pop edm', 79)]

After running this query I realized it would be difficult to run the queries I wanted to because there was a list of genres including sub genres. I knew I had to change all of them to representative of the overarching genres only.

In [109]:
%%sql
SELECT *
FROM artists
WHERE artist_genre LIKE '%latin%';

UPDATE artists
SET artist_genre = 'latin'
WHERE artist_genre LIKE '%latin%';

SELECT *
FROM artists
WHERE artist_genre LIKE '%edm%';

UPDATE artists
SET artist_genre = 'edm'
WHERE artist_genre LIKE '%edm%';

SELECT *
FROM artists
WHERE artist_genre LIKE '%hip hop%' OR artist_genre LIKE '%rap%';

UPDATE artists
SET artist_genre = 'rap'
WHERE artist_genre LIKE '%hip hop%' OR artist_genre LIKE '%rap%';

SELECT *
FROM artists
WHERE artist_name = 'Trevor Daniel';

UPDATE artists
SET artist_genre = 'pop'
WHERE artist_name = 'Trevor Daniel';

SELECT *
FROM artists
WHERE artist_genre LIKE '%rock%';

UPDATE artists
SET artist_genre = 'rock'
WHERE artist_genre LIKE '%rock%';


UPDATE artists
SET artist_genre = 'rap'
WHERE artist_name = 'DripReport';

SELECT *
FROM artists
WHERE artist_name = 'DripReport';

SELECT * 
FROM artists
WHERE artist_name = 'Surf Mesa';

UPDATE artists
SET artist_genre = 'edm'
WHERE artist_name = 'Surf Mesa';

SELECT *
FROM artists
WHERE artist_genre LIKE '%pop%';

UPDATE artists
SET artist_genre = 'pop'
WHERE artist_genre LIKE '%pop%' OR artist_name = 'powfu';

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
5 rows affected.
5 rows affected.
1 rows affected.
1 rows affected.
13 rows affected.
13 rows affected.
1 rows affected.
1 rows affected.
2 rows affected.
2 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
15 rows affected.
16 rows affected.

[]

After runing these SQL queries I edited all of the artist genres to be representative of that artists overarching genre

In [97]:
%%sql
SELECT *
FROM artists
ORDER BY artist_genre;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
38 rows affected.

[('4ofCBoyEiGSePFAG500xev', 'Regard', 'edm', 79),
 ('1lmU3giNF3CSbkVSQmLpHQ', 'Surf Mesa', 'edm', 78),
 ('28gNT5KBp7IjEOQoevXf9N', 'Camilo', 'latin', 88),
 ('1vyhD5VmyZ7KMfW5gqLgo5', 'J Balvin', 'latin', 97),
 ('1mcTU81TzQhprhouKaTkpq', 'Rauw Alejandro', 'latin', 91),
 ('790FomKkXshlbRYZFtlgla', 'KAROL G', 'latin', 88),
 ('4q3ewBCX7sLwd24euuV69X', 'Bad Bunny', 'latin', 100),
 ('4ETSs924pXMzjIeD6E9b4u', 'Surfaces', 'pop', 85),
 ('6qqNVTkY8uBg9cP3Jd7DAH', 'Billie Eilish', 'pop', 96),
 ('6KImCVD70vtIoJWnq6nGn3', 'Harry Styles', 'pop', 90),
 ('2wY79sveU1sp5g7SokKOiI', 'Sam Smith', 'pop', 90),
 ('1Xyo4u8uXC1ZmMpatF05PJ', 'The Weeknd', 'pop', 98),
 ('4GNC7GD6oZMSxPGyXy4MNB', 'Lewis Capaldi', 'pop', 90),
 ('7n2wHs1TKAczGzO7Dd2rGr', 'Shawn Mendes', 'pop', 90),
 ('7uaIm6Pw7xplS8Dy06V6pT', 'Trevor Daniel', 'pop', 85),
 ('0Cp8WN4V8Tu4QJQwCN5Md4', 'BENEE', 'pop', 84),
 ('1uNFoZAHBGtllmzznpCI3s', 'Justin Bieber', 'pop', 95),
 ('5cj0lLjcoR7YOSnhnX0Po5', 'Doja Cat', 'pop', 91),
 ('66W9LaWS0DPdL7Sz8iYGYe', 'JP Saxe', 'pop', 80),
 ('2NjfBq1NflQcKSeiDooVjY', 'Tones And I', 'pop', 88),
 ('6bmlMHgSheBauioMgKv2tn', 'Powfu', 'pop', 87),
 ('6M2wZ9GZgrQXHCFfjv46we', 'Dua Lipa', 'pop', 96),
 ('0xRXCcSX89eobfrshSVdyu', 'MEDUZA', 'pop', 82),
 ('246dkjvS1zLTtiykXe5h60', 'Post Malone', 'rap', 96),
 ('3O5HD95HTEPgoPFOjAb7yV', 'DripReport', 'rap', 78),
 ('7dGJo4pcD2V6oG8kP0tJRR', 'Eminem', 'rap', 95),
 ('1RyvyyTE3xzB2ZywiAwp0i', 'Future', 'rap', 92),
 ('2LIk90788K0zvyj2JJVwkJ', 'Jack Harlow', 'rap', 82),
 ('699OTQXzgjhIYAHMy9RyPD', 'Playboi Carti', 'rap', 85),
 ('0vRvGUQVUjytro0xpb26bs', 'Arizona Zervas', 'rap', 84),
 ('181bsRPaVXVlUKXrxwZfHK', 'Megan Thee Stallion', 'rap', 86),
 ('4r63FhuTkUYltbVAg5TQnk', 'DaBaby', 'rap', 94),
 ('5zctI4wO9XSKS8XwcnqEHk', 'Lil Mosey', 'rap', 88),
 ('757aE44tKEUQEqRuT6GnEB', 'Roddy Ricch', 'rap', 94),
 ('0H39MdGGX6dbnnQPt6NQkZ', 'SAINt JHN', 'rap', 88),
 ('3TVXtAsR1Inumwj472S9r4', 'Drake', 'rap', 99),
 ('04gDigrS5kc9YWfZHwBETP', 'Maroon 5', 'rock', 90),
 ('3YQKmKGau1PzlVlkL1iodx', 'Twenty One Pilots', 'rock', 87)]

I noticed that there is some data redundency in this additionally the foreign key for the genres is missing. Instead of the overarching genre I need to replace it with the genre ID.

In [112]:
%%sql
ALTER TABLE artists
ADD genre_id INT(11) NOT NULL;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
0 rows affected.

[]

I added a genre_id column to the artists table

In [113]:
%%sql

SELECT genre_id, genre_name
FROM genres;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
10 rows affected.

[(1, 'pop'),
 (2, 'rock'),
 (3, 'rap'),
 (4, 'indie'),
 (5, 'edm'),
 (6, 'country'),
 (7, 'r&b'),
 (8, 'latin'),
 (9, 'classical'),
 (10, 'jazz')]

This displays all the genres with their id next to it so I can update the genre_id column in the artists table

In [116]:
%%sql
UPDATE artists
SET genre_id = 1
WHERE artist_genre = 'pop';

UPDATE artists
SET genre_id = 2
WHERE artist_genre = 'rock';

UPDATE artists
SET genre_id = 3
WHERE artist_genre = 'rap';

UPDATE artists
SET genre_id = 4
WHERE artist_genre = 'indie';

UPDATE artists
SET genre_id = 5
WHERE artist_genre = 'edm';

UPDATE artists
SET genre_id = 6
WHERE artist_genre = 'country';

UPDATE artists
SET genre_id = 7
WHERE artist_genre = 'r&b';

UPDATE artists
SET genre_id = 8
WHERE artist_genre = 'latin';

UPDATE artists
SET genre_id = 9
WHERE artist_genre = 'classical';

UPDATE artists
SET genre_id = 10
WHERE artist_genre = 'jazz';

ALTER TABLE artists
DROP artist_genre;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
16 rows affected.
2 rows affected.
13 rows affected.
0 rows affected.
2 rows affected.
0 rows affected.
0 rows affected.
5 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.

[]

In [123]:
%%sql
SELECT *
FROM artists;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
38 rows affected.

[('1Xyo4u8uXC1ZmMpatF05PJ', 'The Weeknd', 98, 1),
 ('3TVXtAsR1Inumwj472S9r4', 'Drake', 99, 3),
 ('0H39MdGGX6dbnnQPt6NQkZ', 'SAINt JHN', 88, 3),
 ('6M2wZ9GZgrQXHCFfjv46we', 'Dua Lipa', 96, 1),
 ('6bmlMHgSheBauioMgKv2tn', 'Powfu', 87, 1),
 ('2NjfBq1NflQcKSeiDooVjY', 'Tones And I', 88, 1),
 ('757aE44tKEUQEqRuT6GnEB', 'Roddy Ricch', 94, 3),
 ('5zctI4wO9XSKS8XwcnqEHk', 'Lil Mosey', 88, 3),
 ('5cj0lLjcoR7YOSnhnX0Po5', 'Doja Cat', 91, 1),
 ('4r63FhuTkUYltbVAg5TQnk', 'DaBaby', 94, 3),
 ('1uNFoZAHBGtllmzznpCI3s', 'Justin Bieber', 95, 1),
 ('0Cp8WN4V8Tu4QJQwCN5Md4', 'BENEE', 84, 1),
 ('7uaIm6Pw7xplS8Dy06V6pT', 'Trevor Daniel', 85, 1),
 ('4ETSs924pXMzjIeD6E9b4u', 'Surfaces', 85, 1),
 ('4q3ewBCX7sLwd24euuV69X', 'Bad Bunny', 100, 8),
 ('181bsRPaVXVlUKXrxwZfHK', 'Megan Thee Stallion', 86, 3),
 ('790FomKkXshlbRYZFtlgla', 'KAROL G', 88, 8),
 ('0vRvGUQVUjytro0xpb26bs', 'Arizona Zervas', 84, 3),
 ('4GNC7GD6oZMSxPGyXy4MNB', 'Lewis Capaldi', 90, 1),
 ('246dkjvS1zLTtiykXe5h60', 'Post Malone', 96, 3),
 ('699OTQXzgjhIYAHMy9RyPD', 'Playboi Carti', 85, 3),
 ('2wY79sveU1sp5g7SokKOiI', 'Sam Smith', 90, 1),
 ('2LIk90788K0zvyj2JJVwkJ', 'Jack Harlow', 82, 3),
 ('28gNT5KBp7IjEOQoevXf9N', 'Camilo', 88, 8),
 ('6KImCVD70vtIoJWnq6nGn3', 'Harry Styles', 90, 1),
 ('04gDigrS5kc9YWfZHwBETP', 'Maroon 5', 90, 2),
 ('1RyvyyTE3xzB2ZywiAwp0i', 'Future', 92, 3),
 ('6qqNVTkY8uBg9cP3Jd7DAH', 'Billie Eilish', 96, 1),
 ('1vyhD5VmyZ7KMfW5gqLgo5', 'J Balvin', 97, 8),
 ('1lmU3giNF3CSbkVSQmLpHQ', 'Surf Mesa', 78, 5),
 ('7n2wHs1TKAczGzO7Dd2rGr', 'Shawn Mendes', 90, 1),
 ('3O5HD95HTEPgoPFOjAb7yV', 'DripReport', 78, 3),
 ('7dGJo4pcD2V6oG8kP0tJRR', 'Eminem', 95, 3),
 ('66W9LaWS0DPdL7Sz8iYGYe', 'JP Saxe', 80, 1),
 ('1mcTU81TzQhprhouKaTkpq', 'Rauw Alejandro', 91, 8),
 ('4ofCBoyEiGSePFAG500xev', 'Regard', 79, 5),
 ('3YQKmKGau1PzlVlkL1iodx', 'Twenty One Pilots', 87, 2),
 ('0xRXCcSX89eobfrshSVdyu', 'MEDUZA', 82, 1)]

I updated the genre_id column in the artist table and then dropped the artist_genre column because that information is already stored in the genres table

# SQL 1

## SQL #1

Question: Create a table that displays who the top performing artists are?

Business Justification: By seeing the artists who have the most songs in the top 50 chart, we can see which artist creates the most top tracks. We will pursue that artist to try to create deals and try to tailor some of the Apple Music marketing with the use of those better performing artists. 

SQL features: Common Table Expression, Join, Group by

In [124]:
%%sql
#CTE to see which artists have the most top songs
WITH artist_top_song_count AS (
    SELECT artist_name, track_name
    FROM top_50_songs 
    JOIN artists 
        ON artists.artist_id = top_50_songs.artist_id
)

SELECT artist_name, COUNT(*) AS num_top_songs
FROM artist_top_song_count
GROUP BY artist_name
ORDER BY num_top_songs DESC;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
38 rows affected.

[('Bad Bunny', 5),
 ('Dua Lipa', 3),
 ('The Weeknd', 2),
 ('Doja Cat', 2),
 ('DaBaby', 2),
 ('Lewis Capaldi', 2),
 ('Billie Eilish', 2),
 ('J Balvin', 2),
 ('Tones And I', 1),
 ('Surfaces', 1),
 ('Sam Smith', 1),
 ('Surf Mesa', 1),
 ('MEDUZA', 1),
 ('Roddy Ricch', 1),
 ('Jack Harlow', 1),
 ('Shawn Mendes', 1),
 ('Lil Mosey', 1),
 ('Megan Thee Stallion', 1),
 ('Camilo', 1),
 ('DripReport', 1),
 ('KAROL G', 1),
 ('Harry Styles', 1),
 ('Eminem', 1),
 ('Drake', 1),
 ('Arizona Zervas', 1),
 ('Maroon 5', 1),
 ('JP Saxe', 1),
 ('SAINt JHN', 1),
 ('Justin Bieber', 1),
 ('Future', 1),
 ('Rauw Alejandro', 1),
 ('BENEE', 1),
 ('Post Malone', 1),
 ('Travis Scott', 1),
 ('Powfu', 1),
 ('Trevor Daniel', 1),
 ('Playboi Carti', 1),
 ('Twenty One Pilots', 1)]

## SQL #1

Reccomendaion:

Based on these results we see that the artist that performs the most top songs is Bad Bunny. As for my reccomendation, I believe that Apple Music should strike some sort of deal with Bad Bunny, for example, have him release his music exclusively on Apple Music for a week before releasing on other platforms. Additionally, if Bad Bunny would not agree to that, Dua Lipa,  who follows Bad Bunny's 5 top songs with 3 top songs, could be another target for a similar promotional plan.

# SQL 2

## SQL #2

Question: Create a classification for popular artists, who are artists that have a popularity rating greater than that of industry standard.

Business Justification: We can filter out the artists that have a popularity rating lower than that of the average for the specific genre. Then by seeing which artists have the highest popularity rating we can see which artists have a the majority of people listening to their music. This will indicate which artists are good to pursue in partnerships regardless if they do not have many songs in the current top 50 chart.

SQL Features: Case, Common Table Expression, Join, Window

In [125]:
%%sql
WITH artist_genre_popularity AS (
    SELECT 
        artist_name, 
        genres.genre_name,
        artist_popularity,
        AVG(artist_popularity) OVER(PARTITION BY artists.genre_id) AS avg_artist_popularity_per_genre,

            CASE
                WHEN artists.artist_popularity < 90 THEN 'Mildly Popular'
                WHEN artists.artist_popularity BETWEEN 90 AND 95 THEN 'More Popular'
                ELSE 'Extremely Popular'
            END AS 'popularity_level'

    FROM artists
    JOIN genres
        ON artists.genre_id = genres.genre_id
)

SELECT *
FROM artist_genre_popularity
WHERE artist_popularity > avg_artist_popularity_per_genre
ORDER BY artist_popularity DESC;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
20 rows affected.

[('Bad Bunny', 'latin', 100, Decimal('92.8000'), 'Extremely Popular'),
 ('Drake', 'rap', 99, Decimal('89.9286'), 'Extremely Popular'),
 ('Travis Scott', 'rap', 98, Decimal('89.9286'), 'Extremely Popular'),
 ('The Weeknd', 'pop', 98, Decimal('89.1875'), 'Extremely Popular'),
 ('J Balvin', 'latin', 97, Decimal('92.8000'), 'Extremely Popular'),
 ('Dua Lipa', 'pop', 96, Decimal('89.1875'), 'Extremely Popular'),
 ('Post Malone', 'rap', 96, Decimal('89.9286'), 'Extremely Popular'),
 ('Billie Eilish', 'pop', 96, Decimal('89.1875'), 'Extremely Popular'),
 ('Justin Bieber', 'pop', 95, Decimal('89.1875'), 'More Popular'),
 ('Eminem', 'rap', 95, Decimal('89.9286'), 'More Popular'),
 ('Roddy Ricch', 'rap', 94, Decimal('89.9286'), 'More Popular'),
 ('DaBaby', 'rap', 94, Decimal('89.9286'), 'More Popular'),
 ('Future', 'rap', 92, Decimal('89.9286'), 'More Popular'),
 ('Doja Cat', 'pop', 91, Decimal('89.1875'), 'More Popular'),
 ('Maroon 5', 'rock', 90, Decimal('88.5000'), 'More Popular'),
 ('Lewis Capaldi', 'pop', 90, Decimal('89.1875'), 'More Popular'),
 ('Sam Smith', 'pop', 90, Decimal('89.1875'), 'More Popular'),
 ('Harry Styles', 'pop', 90, Decimal('89.1875'), 'More Popular'),
 ('Shawn Mendes', 'pop', 90, Decimal('89.1875'), 'More Popular'),
 ('Regard', 'edm', 79, Decimal('78.5000'), 'Mildly Popular')]

## SQL #2

Reccomendation: From this table we see once again that Bad Bunny has a high popularity rating that is higher than the genre average.

If looking at just the popularity rating, Bad Bunny would be the clear cut pick for a branding deal. 

However, artists like Travis Scott, Drake, and The Weeknd all are categorized as extremely popular and have a popularity rating that is about 9-10 points higher than their respecitve genre average. Therefore, these would be the best artists for Apple Music to pursue to get deals with or create playlist that are more tailored to those listening to these artists.

# SQL 3

## SQL #3

Question: Create a query that displays the the top genres and the percentage of each age group that listens to that genre.

Business Justification: By showing the most popular genres and their respective age groups, we can choose which age group to market towards and form a target market for Apple Music using that. Additionally, marketing can be ramped up for specific genres in specific age groups while other genres and age groups not so much.

SQL features: View, Join, Group By

In [81]:
%%sql
CREATE OR REPLACE VIEW top_songs_by_artists_with_genre AS
    SELECT artists.artist_name, top_50_songs.track_name, genres.genre_id, genres.genre_name, genres.age_16_19, 
        genres.age_20_24, genres.age_25_34, genres.age_35_44, genres.age_45_54, genres.age_55_64, genres.age_65_plus
    FROM top_50_songs
    JOIN artists
        ON top_50_songs.artist_id = artists.artist_id
    JOIN genres
        ON artists.genre_id = genres.genre_id;

SELECT 
    genre_id, genre_name, age_16_19, 
    age_20_24, age_25_34, age_35_44,
    age_45_54, age_55_64, age_65_plus, 
    COUNT(*) AS num_of_top_songs_in_genre
FROM top_songs_by_artists_with_genre
GROUP BY genre_id
ORDER BY COUNT(*) DESC;

 * mysql://admin:***@lmu-sql.crkxqhoxro46.us-east-2.rds.amazonaws.com/sql_project
0 rows affected.
5 rows affected.

[(1, 'pop', 52, 54, 56, 46, 42, 25, 19, 21),
 (3, 'rap', 48, 54, 42, 33, 15, 5, 1, 14),
 (8, 'latin', 30, 35, 36, 34, 21, 13, 5, 10),
 (5, 'edm', 20, 33, 15, 21, 9, 5, 1, 3),
 (2, 'rock', 26, 36, 44, 46, 62, 60, 48, 2)]

## SQL #3

Reccomendation: 

We see by far that pop has the most songs in the top 50 charts. Therefore if resources were to be given towards marketing the most popular genre it would be pop. Additionally, the age groups demonstrate that more than half of those from age 16-34 listen to pop music. Therefore, marketing should be done towards Millenials and Gen Z.